name: Build and Upload Release Asset to AWS S3

on:
  release:
    types: [created]   # Trigger only when a release is created manually
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to use for manual workflow test'
        required: true
        default: 'test'

permissions:
  contents: write 
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prometheon-access

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js (24.x)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # Install dependencies
      - name: Install dependencies
        run: npm ci --ignore-scripts

      # Build the app
      - name: Build drill-frontend
        run: npm run build

      # Archive build output into a zip file
      - name: Create zip archive
        run: zip -r drill-frontend.zip dist

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.SFOE_DRILL_FRONTEND_PIPELINE_ROLE }}
          aws-region: eu-central-1  

      # Upload zip to S3
      - name: Upload zip to S3
        env:
          S3_BUCKET: ${{ vars.SFOE_DRILL_FRONTEND_s3_BUCKET }}
        run: |
          aws s3 cp drill-frontend.zip s3://$S3_BUCKET/drill-frontend-${{ github.event.release.tag_name || github.event.inputs.tag_name }}.zip